IMAGE_SIZE = 256
LINE_WIDTH = 5

RAW_DATA_SOURCE = "./raw_data"
TRAINING_SET_SIZE = 20
TRAINING_BATCH_SIZE = 5
VALIDATION_SET_SIZE = 30

TRAINING_SET_SIZE = TRAINING_SET_SIZE - (TRAINING_SET_SIZE % TRAINING_BATCH_SIZE)